version: "3"

services: 
    master:
        build: ./jenkins-master
        ports:
            - "50000:50000"
        volumes:
            - /Users/maheshgummaraju/jenkins-data:/var/jenkins_home
        networks: 
            - jenkins-net
    nginx:
        build: ./jenkins-nginx
        ports:
            - "80:80"
        networks: 
            - jenkins-net
    proxy:
        build: ./docker-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            jenkins-net:
                aliases: 
                    - proxy1
    slave:
        build: ./jenkins-slave
                      
networks: 
    jenkins-net:
